import { Video } from '@/src/types/video';

export const mockVideos: Array<Video> = [
  {
    id: '1',
    title: 'Sunrise Over Alpine Lakes: Peaceful Landscapes',
    author: 'Nature Channel',
    durationSec: 1847,
    thumbnail: 'https://picsum.photos/640/360?random=1',
    publishedAt: '2024-07-02T10:30:00Z',
    views: 125000,
    description:
      'Immerse yourself in the tranquil beauty of alpine lakes at dawn, featuring crystal-clear waters and majestic mountain reflections',
  },
  {
    id: '2',
    title: 'Cozy Rainy Forest Walk for Relaxation',
    author: 'Wildlife Explorer',
    durationSec: 1234,
    thumbnail: 'https://picsum.photos/640/360?random=2',
    publishedAt: '2024-08-15T14:20:00Z',
    views: 89000,
    description:
      'Take a peaceful walk through misty forests as gentle rain creates a soothing atmosphere perfect for relaxation',
  },
  {
    id: '3',
    title: 'Iconic Cityscapes: Golden Hour in New York',
    author: 'Urban Nature',
    durationSec: 51,
    thumbnail: 'https://picsum.photos/640/360?random=3',
    publishedAt: '2024-09-10T09:15:00Z',
    views: 156000,
    description: 'Experience the magic of golden hour in iconic cityscapes, where urban landscapes meet natural light',
  },
  {
    id: '4',
    title: 'Desert Dunes: Wind and Light',
    author: 'Desert Dreams',
    durationSec: 1789,
    thumbnail: 'https://picsum.photos/640/360?random=4',
    publishedAt: '2024-09-29T16:45:00Z',
    views: 67000,
    description:
      'Witness the ever-changing patterns of desert dunes as wind and light create mesmerizing natural sculptures',
  },
  {
    id: '5',
    title: 'Coastal Cliffs: Waves and Seabreeze',
    author: 'Ocean Wonders',
    durationSec: 1987,
    thumbnail: 'https://picsum.photos/640/360?random=5',
    publishedAt: '2024-10-12T11:30:00Z',
    views: 98000,
    description:
      'Feel the power of ocean waves crashing against dramatic coastal cliffs while seabreeze carries the salty air',
  },
  {
    id: '6',
    title: 'Misty Mountains: Clouds Rolling Over Peaks',
    author: 'Mountain Mystique',
    durationSec: 2156,
    thumbnail: 'https://picsum.photos/640/360?random=6',
    publishedAt: '2024-11-08T13:20:00Z',
    views: 74000,
    description:
      'Watch as ethereal clouds gracefully roll over mountain peaks, creating a mystical and serene atmosphere',
  },
  {
    id: '7',
    title: 'Autumn in Kyoto: Quiet Streets and Temples',
    author: 'Cultural Landscapes',
    durationSec: 1876,
    thumbnail: 'https://picsum.photos/640/360?random=7',
    publishedAt: '2024-11-25T08:00:00Z',
    views: 112000,
    description:
      "Stroll through Kyoto's peaceful streets during autumn, where ancient temples meet vibrant fall colors",
  },
  {
    id: '8',
    title: 'Nordic Fjords: Calm Waters and Steep Valleys',
    author: 'Nordic Nature',
    durationSec: 673,
    thumbnail: 'https://picsum.photos/640/360?random=8',
    publishedAt: '2024-12-22T15:10:00Z',
    views: 85000,
    description: 'Discover the breathtaking beauty of Nordic fjords with their calm waters and dramatic steep valleys',
  },
  {
    id: '9',
    title: 'Snowy Forest Cabin: Your Cozy Winter Escape',
    author: 'Winter Wonderland',
    durationSec: 1345,
    thumbnail: 'https://picsum.photos/640/360?random=9',
    publishedAt: '2025-01-14T12:30:00Z',
    views: 143000,
    description: 'Escape to a cozy snowy forest cabin where winter creates a magical and peaceful retreat',
  },
  {
    id: '10',
    title: 'Tropical Islands: Turquoise Lagoons and Palms',
    author: 'Tropical Paradise',
    durationSec: 1456,
    thumbnail: 'https://picsum.photos/640/360?random=10',
    publishedAt: '2025-02-03T17:45:00Z',
    views: 69000,
    description: 'Relax in tropical paradise with crystal-clear turquoise lagoons and swaying palm trees',
  },
  {
    id: '11',
    title: 'City Nights: Neon Lights and Rainy Streets',
    author: 'Urban Explorer',
    durationSec: 162,
    thumbnail: 'https://picsum.photos/640/360?random=11',
    publishedAt: '2025-03-21T14:15:00Z',
    views: 76000,
    description: 'Experience the vibrant energy of city nights with neon lights reflecting on rain-soaked streets',
  },
  {
    id: '12',
    title: 'Great Plains: Endless Skies and Rolling Fields',
    author: 'Prairie Dreams',
    durationSec: 420,
    thumbnail: 'https://picsum.photos/640/360?random=12',
    publishedAt: '2025-05-09T10:00:00Z',
    views: 95000,
    description: 'Vast open spaces where endless skies meet rolling fields, creating a sense of infinite freedom',
  },
  {
    id: '13',
    title: 'Hidden Waterfalls: Secret Trails and Fresh Mist',
    author: 'Waterfall Hunter',
    durationSec: 1234,
    thumbnail: 'https://picsum.photos/640/360?random=13',
    publishedAt: '2025-06-18T16:30:00Z',
    views: 82000,
    description: 'Follow secret trails to discover hidden waterfalls where fresh mist creates a refreshing natural spa',
  },
  {
    id: '14',
    title: 'Around The World by Train: Windows to Landscapes',
    author: 'Railway Journeys',
    durationSec: 524,
    thumbnail: 'https://picsum.photos/640/360?random=14',
    publishedAt: '2025-08-02T11:20:00Z',
    views: 71000,
    description:
      'Embark on an epic train journey around the world, watching diverse landscapes unfold through your window',
  },
  {
    id: '15',
    title: 'European Capitals: A Walk Through History',
    author: 'Historic Landscapes',
    durationSec: 1456,
    thumbnail: 'https://picsum.photos/640/360?random=15',
    publishedAt: '2025-10-18T09:45:00Z',
    views: 108000,
    description:
      'Walk through the historic streets of European capitals where every corner tells a story of centuries past',
  },
  {
    id: '16',
    title: 'Quick Morning Stretch Routine',
    author: 'Health & Wellness',
    durationSec: 180,
    thumbnail: 'https://picsum.photos/640/360?random=16',
    publishedAt: '2025-10-20T07:00:00Z',
    views: 45000,
    description: 'A quick 3-minute morning stretch routine to energize your day',
  },
  {
    id: '17',
    title: 'Coffee Brewing Tips',
    author: 'Coffee Masters',
    durationSec: 828,
    thumbnail: 'https://picsum.photos/640/360?random=17',
    publishedAt: '2025-10-21T08:30:00Z',
    views: 32000,
    description: 'Learn the perfect coffee brewing technique in just 4 minutes',
  },
  {
    id: '18',
    title: 'Sunset Timelapse - 2 Minutes',
    author: 'Nature Shorts',
    durationSec: 120,
    thumbnail: 'https://picsum.photos/640/360?random=18',
    publishedAt: '2025-10-22T19:30:00Z',
    views: 28000,
    description: 'Beautiful sunset captured in a stunning 2-minute timelapse',
  },
];
